import * as AlertDialog from "@radix-ui/react-alert-dialog";
import Show from "../components/Show";
import Card from "../components/Card";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Show />
        <Card />
        <Card />
        <Card />
      </main>
    </>
  );
}
